/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';


import {
  ITabsData,
} from './components/tabs/tabs';


declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface TeddytApp {

    }

    interface TeddytHeader {
      'projectName': string;
    }

    interface TeddytTab {
      'isTabActive': boolean;
      'tabIcon': string;
      'tabName': string;
    }

    interface TeddytTabs {
      'tabsData': ITabsData;
    }
  }


    interface HTMLTeddytAppElement extends StencilComponents.TeddytApp, HTMLStencilElement {}

    var HTMLTeddytAppElement: {
      prototype: HTMLTeddytAppElement;
      new (): HTMLTeddytAppElement;
    };
    

    interface HTMLTeddytHeaderElement extends StencilComponents.TeddytHeader, HTMLStencilElement {}

    var HTMLTeddytHeaderElement: {
      prototype: HTMLTeddytHeaderElement;
      new (): HTMLTeddytHeaderElement;
    };
    

    interface HTMLTeddytTabElement extends StencilComponents.TeddytTab, HTMLStencilElement {}

    var HTMLTeddytTabElement: {
      prototype: HTMLTeddytTabElement;
      new (): HTMLTeddytTabElement;
    };
    

    interface HTMLTeddytTabsElement extends StencilComponents.TeddytTabs, HTMLStencilElement {}

    var HTMLTeddytTabsElement: {
      prototype: HTMLTeddytTabsElement;
      new (): HTMLTeddytTabsElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'teddyt-app': JSXElements.TeddytAppAttributes;
    'teddyt-header': JSXElements.TeddytHeaderAttributes;
    'teddyt-tab': JSXElements.TeddytTabAttributes;
    'teddyt-tabs': JSXElements.TeddytTabsAttributes;
    }
  }

  namespace JSXElements {

    export interface TeddytAppAttributes extends HTMLAttributes {

    }

    export interface TeddytHeaderAttributes extends HTMLAttributes {
      'onNewProject'?: (event: CustomEvent<null>) => void;
      'onProjectNameChanged'?: (event: CustomEvent<string>) => void;
      'onSaveProject'?: (event: CustomEvent<string>) => void;
      'projectName'?: string;
    }

    export interface TeddytTabAttributes extends HTMLAttributes {
      'isTabActive'?: boolean;
      'onTabActive'?: (event: CustomEvent<string>) => void;
      'onTabClosed'?: (event: CustomEvent<string>) => void;
      'tabIcon'?: string;
      'tabName'?: string;
    }

    export interface TeddytTabsAttributes extends HTMLAttributes {
      'tabsData'?: ITabsData;
    }
  }

  interface HTMLElementTagNameMap {
    'teddyt-app': HTMLTeddytAppElement
    'teddyt-header': HTMLTeddytHeaderElement
    'teddyt-tab': HTMLTeddytTabElement
    'teddyt-tabs': HTMLTeddytTabsElement
  }

  interface ElementTagNameMap {
    'teddyt-app': HTMLTeddytAppElement;
    'teddyt-header': HTMLTeddytHeaderElement;
    'teddyt-tab': HTMLTeddytTabElement;
    'teddyt-tabs': HTMLTeddytTabsElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

